version: '3'

services:
  node-server:
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres-database
      - DB_PORT=5432
      - DB_DATABASE=database_1
      - DB_USER=root
      - DB_PASSWORD=root
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: node-boilerplate
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev

  postgres-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_1
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
